### ISSUE TITLE
SYSEX 3 error, also Computed Checksum

### ISSUE THREAD

**Issue by Ang3lus123** [ValdemarOrn/Mp2Editor#3]
When connecting the mp2 to my computer, I can change presets but not load them into the computer, just the prgrm up and bank up and down buttons are working.

whenever i try to send the library from the Mp-2 I get Computed checksum does match program value

midi,channel is set correctly also INput and output midi device are set correctly.

these are the error logs

==== Computed checksum does match program value ====
   at Mp2Editor.Core.Mp2Sysex.ParseProgram(Byte[] data)
   at Mp2Editor.MainViewModel.ReceiveProgramHandler(Byte[] data)
   at Mp2Editor.Core.MidiConnection.HandleSysex(SysExMessage msg)
   at Midi.InputDevice.SysExHandler.Invoke(SysExMessage msg)
   at Midi.InputDevice.InputCallback(HMIDIIN hMidiIn, MidiInMessage wMsg, UIntPtr dwInstance, UIntPtr dwParam1, UIntPtr dwParam2)

**Comment by maxcomperatore** [comment]
The exception `Computed checksum does match program value` (which has a minor typo in the codebase for "does not match") occurs inside `Mp2Sysex.ParseProgram(Byte[] data)`.

Looking at `Mp2Editor.Core/Mp2Sysex.cs` around line 101:

```csharp
public static int ComputeChecksum(byte[] data, bool includesSysexStart, bool includesChecksumAndSysexEnd)
{
    if (includesSysexStart)
        data = data.Skip(1).ToArray();
    if (includesChecksumAndSysexEnd)
        data = data.Take(data.Length - 2).ToArray();

    int val = 0;
    for (int i = 0; i < data.Length; i++)
    {
        val = val + data[i];
    }

    var result = (~(val & 0xff) + 1) & 0xFF;
    return result & 0x7F;
}
```

### Why this fails on incoming MP-2 dumps:

1. **The Header Bytes Are Being Summed:**
`data.Skip(1)` only removes the initial `0xF0`. The checksum loop then sums `data[1]` through `data[data.Length - 3]`. This includes:
- Byte 1: Manufacturer ID (0x15)
- Byte 2: MIDI Channel (0x00 to 0x0F)
- Byte 3: Model ID
- Byte 4: Command
- Byte 5: Program Number

In standard ADA SysEx implementations, the checksum is calculated **only over the parameter data payload** (starting at byte offset 6), excluding the 6-byte transmission header. If the software sums the header bytes while the hardware firmware excludes them, `computedChecksum` will never match `expectedChecksum`.

2. **MIDI Channel Mismatch:**
Because Byte 2 is the MIDI channel, if your MP-2 physical unit transmits on any channel other than Channel 1 (0x00), the byte sum changes by the channel number value, triggering an immediate mismatch.

### How to test and verify your dump:
If you capture the raw `.syx` dump from your MP-2 using a MIDI monitor or sysex utility, you can inspect the exact byte offsets and recalculate the checksum in our free web inspector:
https://bipluk.com/tools/sysex-checksum-splitter

You can drop the `.syx` file in to see the exact byte sum, verify what byte sits at index `data.Length - 2`, and repair the checksum byte if the dump got corrupted during transfer.
